CREATE TABLE IF NOT EXISTS ep_debtor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(200) NOT NULL,
    birth_date DATE,
    debt_amount NUMERIC(14,2) NOT NULL CHECK (debt_amount >= 0),
    reason VARCHAR(1000) NOT NULL,
    documents VARCHAR(2000),
    created_by VARCHAR(80) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ep_referral (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    debtor_id BIGINT NOT NULL REFERENCES ep_debtor(id),
    status VARCHAR(32) NOT NULL DEFAULT 'CREATED'
        CHECK (status IN ('CREATED', 'HANDED_TO_CONVOY', 'CANCELLED')),
    idempotency_key VARCHAR(80) NOT NULL UNIQUE,
    created_by VARCHAR(80) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ep_resident (
    id VARCHAR(10) PRIMARY KEY,
    referral_id BIGINT NOT NULL UNIQUE REFERENCES ep_referral(id),
    status VARCHAR(32) NOT NULL DEFAULT 'ARRIVED'
        CHECK (status IN ('ARRIVED', 'ASSIGNED', 'TRANSFORMED')),
    arrived_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(80) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ep_zone (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    capacity INTEGER NOT NULL CHECK (capacity > 0),
    transformation_coefficient NUMERIC(5,3) NOT NULL CHECK (transformation_coefficient > 0),
    predicted_hours NUMERIC(6,2) NOT NULL CHECK (predicted_hours > 0),
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS ep_zone_assignment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resident_id VARCHAR(10) NOT NULL REFERENCES ep_resident(id),
    zone_id BIGINT NOT NULL REFERENCES ep_zone(id),
    transformation_percent INTEGER NOT NULL DEFAULT 0 CHECK (transformation_percent BETWEEN 0 AND 100),
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    left_at TIMESTAMPTZ,
    updated_by VARCHAR(80) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS ep_one_active_assignment
    ON ep_zone_assignment(resident_id) WHERE left_at IS NULL;
CREATE INDEX IF NOT EXISTS ep_assignment_zone_active
    ON ep_zone_assignment(zone_id, left_at);

CREATE TABLE IF NOT EXISTS ep_transformation_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_id BIGINT NOT NULL REFERENCES ep_zone_assignment(id),
    previous_percent INTEGER NOT NULL CHECK (previous_percent BETWEEN 0 AND 100),
    new_percent INTEGER NOT NULL CHECK (new_percent BETWEEN 0 AND 100),
    changed_by VARCHAR(80) NOT NULL,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ep_transformation_history_assignment_idx
    ON ep_transformation_history(assignment_id, changed_at DESC);

CREATE TABLE IF NOT EXISTS ep_shearing (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resident_id VARCHAR(10) NOT NULL UNIQUE REFERENCES ep_resident(id),
    wool_kg NUMERIC(10,1),
    predicted_energy_kwh NUMERIC(12,1),
    status VARCHAR(32) NOT NULL DEFAULT 'WAITING'
        CHECK (status IN ('WAITING', 'COMPLETED')),
    created_by VARCHAR(80) NOT NULL,
    completed_by VARCHAR(80),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE ep_shearing ADD COLUMN IF NOT EXISTS completed_by VARCHAR(80);

CREATE TABLE IF NOT EXISTS ep_energy_shift (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shift_code VARCHAR(80) NOT NULL UNIQUE,
    actual_kwh NUMERIC(14,1) NOT NULL CHECK (actual_kwh >= 0),
    delivery_status VARCHAR(32) NOT NULL
        CHECK (delivery_status IN ('DELIVERED', 'PENDING')),
    delivery_attempts INTEGER NOT NULL DEFAULT 1,
    created_by VARCHAR(80) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ep_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor VARCHAR(80) NOT NULL,
    action VARCHAR(80) NOT NULL,
    entity_type VARCHAR(80) NOT NULL,
    entity_id VARCHAR(80),
    details VARCHAR(2000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ep_referral_status_idx ON ep_referral(status);
CREATE INDEX IF NOT EXISTS ep_debtor_full_name_idx ON ep_debtor(LOWER(full_name));
CREATE INDEX IF NOT EXISTS ep_resident_status_idx ON ep_resident(status);
CREATE INDEX IF NOT EXISTS ep_audit_created_idx ON ep_audit_log(created_at DESC);
CREATE INDEX IF NOT EXISTS ep_energy_delivery_idx
    ON ep_energy_shift(delivery_status, updated_at);

INSERT INTO ep_zone(name, capacity, transformation_coefficient, predicted_hours)
VALUES
    ('Север', 12, 1.15, 8.0),
    ('Восток', 10, 1.05, 10.0),
    ('Запад', 8, 0.95, 12.0),
    ('Юг', 14, 0.90, 14.0)
ON CONFLICT (name) DO NOTHING;
